### PR TITLE
Extend generated OpenAPI specs with query params

### LINKED ISSUE #149: Request parameters are not included in OpenAPI spec
Given a view with:

```python
@validate_params(
    {
        'type': 'object',
        'properties': {
            'account_id': {'type': 'string'},
            'brand_id': {'type': 'string'},
        },  
        'required': ['brand_id', 'account_id'],
    }
)
```

Then run:

```sh
$ env/bin/acceptable lint api.json myapp.webapi --quiet --update
```
Produces `api.json` with the expected `"params_schema"` for that view. But `openapi.yaml` otoh, contains just `get.parameters: []`.

### PR DESCRIPTION
**Pull request by maxiberta**
Fixes #149.

### CODE REVIEW

**Comment by maxiberta** [comment]
Hm, I wonder why the black check failed; cannot reproduce locally.

**Comment by maxiberta** [comment]
> Hm, I wonder why the black check failed; cannot reproduce locally.

I know! The action runs with `--skip-magic-trailing-comma` but `make lint` does not ;-).

**Review by verterok — APPROVED** [review]
LGTM

**Review by shanepelletier — APPROVED** [review]
LGTM!

**Review by lofidevops — APPROVED** [review]
Huzzah!

**Pull request merged**
